title: Open Protocol
description: Enabling seamless integration between AI systems and data sources with MCP-first architecture
url: https://openprotocol.ai
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
